FROM bitnami/spark:3.3.0

USER root

# Install Python 3 and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    ln -sf /usr/bin/pip3 /usr/bin/pip

# Install required packages
RUN pip install numpy pandas xgboost==1.6.2 pyarrow scikit-learn

# Install PySpark XGBoost integration
RUN pip install sparkxgb

WORKDIR /opt/bitnami/spark

USER 1001